#!/bin/bash
#======================================================================
#- IMPLEMENTATION
#-    version         profiler (https://www.washington.edu/) 0.3
#-    author          Varik Hoang <varikmp@uw.edu> and Tanmay Shah <tanmay@uw.edu>
#-    copyright       Copyright (c) https://www.washington.edu/
#-    license         GNU General Public License
#======================================================================
#  HISTORY
#     2021/05/19 : varikmp - script creation
#     2021/08/12 : varikmp - implemented time steps for sampling
#======================================================================
#  OPTION
#    PROFILER_OUTPUT_DIR # specify the output directory
#    PROFILER_TIME_STEPS # specify the time step each second
#======================================================================

function help()
{
    echo "Usage: $0 COMMAND"
    echo "       PROFILER_OUTPUT_DIR: output directory for the profiling"
    echo "       PROFILER_TIME_STEPS: time steps in seconds (must be non-negative integer)"
    echo "Example:"
    echo "       PROFILER_OUTPUT_DIR=/tmp"
    echo "       PROFILER_TIME_STEPS=1"
    echo "       $0 \"sleep 10\""
}

if [ "$#" -eq "0" ]
then
    help
    exit
fi

PROFILER_OUTPUT_DIR=$(printenv PROFILER_OUTPUT_DIR)
PROFILER_TIME_STEPS=$(printenv PROFILER_TIME_STEPS)
if [ -z "$PROFILER_OUTPUT_DIR" ]
then
    PROFILER_OUTPUT_DIR=./.cprofiles
fi
if [ -z "$PROFILER_TIME_STEPS" ] || \
   ! [[ "$PROFILER_TIME_STEPS" =~ ^[0-9]+$ ]] || [ $PROFILER_TIME_STEPS -lt 1 ]
then
    PROFILER_TIME_STEPS=0
fi




#echo $PROFILER_TIME_STEPS
if [ $PROFILER_TIME_STEPS -eq 0 ]
then
    python3 ./rudataall-psutil.py -"$VERBOSITY" $PROFILER_OUTPUT_DIR
    eval $@
    python3 ./rudataall-psutil.py -"$VERBOSITY" $PROFILER_OUTPUT_DIR
else
    eval $@ & PID=$!
    while kill -0 $PID > /dev/null 2>&1
    do
        #____ This stub does not account for profiling overhead
        #python3 ./rudataall-psutil.py -"$VERBOSITY" $PROFILER_OUTPUT_DIR
        #sleep $PROFILER_TIME_STEPS
        #____

        #____ This stub accounts for profiling overhead
        	t1=$(date '+%s%3N')
          python3 ./rudataall-psutil.py -"$VERBOSITY" $PROFILER_OUTPUT_DIR
          t2=$(date '+%s%3N')
          let diff=$t2-$t1
          let profile_time=`echo diff / 1000 | bc -l`
          let sleep_time=$PROFILER_TIME_STEPS-$profile_time
          #sleep_time=`echo $sleep_time / 1000 | bc -l`
          if [ $sleep_time -gt 0 ]
          then
            sleep $sleep_time
          fi
        #____
    done
fi
